### ISSUE TITLE
ImportError: No module named core.parsing

### ISSUE THREAD

**Issue by amandalmia14** [STLInspector/STLInspector#12]
![image](https://user-images.githubusercontent.com/13628323/65043024-c1f67180-d977-11e9-9f60-eb6ed359394c.png)

After creating an environment, when I enter the command `stlinspector .` It throws an error, 

```
from ..core.parsing import *
ImportError: No module named core.parsing
```

OS: Windows 10, Python: 2.7.9

@HendrikRoehm

**Comment by HendrikRoehm** [comment]
Hi @amandalmia14, thanks for sharing. I have to investigate this error.

As far as I can see it you are using anaconda. Can you give me the list of commands you use to start the environment and install stlinspector in it?

**Comment by amandalmia14** [comment]
@HendrikRoehm 

I used `conda create -n stl_inspector_test python=2.7.9` to create an environment in Anaconda.
After activating the environment, I installed `pip install STLInspector`

**Comment by HendrikRoehm** [comment]
@amandalmia14 sorry for the delay. I will be able to dig deeper today. Have you found any helpful information in the meantime?

**Comment by amandalmia14** [comment]
@HendrikRoehm No luck :(

**Comment by HendrikRoehm** [comment]
I can reproduce the problem. The quickfix seems to be using stlinspector in development mode. You have to clone the code and follow the steps in `doc/development.md` with `python setup.py develop`.

**Comment by HendrikRoehm** [comment]
Found the issue. We did not package all required python files into the distribution package. New version should be available via pip in some minutes.

**Comment by HendrikRoehm** [comment]
New package version is available: `pip install --upgrade stlinspector`
