### ISSUE TITLE
An error ocurring when loading a test

### ISSUE THREAD

**Issue by ivan-gavran** [STLInspector/STLInspector#8]
After installing STLInspector (using pip, as specified in the instructions) and starting a `new visual inspection`, I receive an error `Z3Exception: Python bool, int, long or float expected`. The error originates from `(t, kind) = get_test(z3.And(f_neg, m_pos), z3.And(f_pos, m_neg))` in function generate_test.

On the other hand, visual inspection works with the provided example. But as soon as I modify it and save it (for example, changing the operator from `F` to `G`, the same error occurs).

What could be possible reasons for it?

**Comment by HendrikRoehm** [comment]
Hi gergia,
thanks for submitting this issue. I have uploaded a new version, which should resolve this error. Please test and confirm.
I am happy to see that you are interested in STLInspector. If there is anything else I can help you with, please reach out to me.

**Comment by ivan-gavran** [comment]
I tested - it works now, thanks for the quick solution.
Compliments for the great project!
