### ISSUE TITLE
Changing the grammar

### ISSUE THREAD

**Issue by ivan-gavran** [STLInspector/STLInspector#9]
Hi,

what would be the proper way to change the grammar?
I tried changing the `TemporalLogic.g4` file and then compiling it with antlr to get .py files.
That produced file with wrong imports (but that was easily fixed by hand) but also some problem in serialization. 

I don't know how informative the trace is, but maybe it is telling more than I can read from it
`Exception: ('Could not deserialize ATN with UUID: 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).', UUID('59627784-3be5-417a-b9eb-8131a7286089'), UUID('aadb8d7e-aeef-4415-ad2b-8204d6cf042e'))
`

**Comment by HendrikRoehm** [comment]
Hi Gergia,
I do not understand the error message. You could look at the branch improve_parseerrors. In that branch, I habe improved the language significantly. Could you please try to checkout the branch and just compile the grammar? If this does not work, we can try to document the build process together such that it works for you. After we have tackled the improvement of the build documentation, you can then change it accordingly.

**Comment by ivan-gavran** [comment]
sorry for the late response, I missed the notification: I am interested in improving and documenting the build process. (the branch improve_parseerrors really is much better, but I'd like to be able to modify further)

**Comment by HendrikRoehm** [comment]
We can try to finalize the improve_parseerrors branch and merge it into the master branch. Did you try to build with antlr the .g4 file from the improve_parseerrors branch?

**Comment by ivan-gavran** [comment]
Yes - the same happens (complaining about serialized_UUID).
Concretely, in steps:
 1. I changed something in the grammar (added 'finally' as an option for TOKEN_FINALLY)
 2. I ran `antlr4 -Dlanguage=Python2 TemporalLogic.g4` . new files were created. when inspecting the differences, I notice that the one downloaded from the repo is generated by Antlr 4.5.2, while I was using 4.7.2

Do you modify anything by hand after running Antlr?

**Comment by HendrikRoehm** [comment]
Hi gergia, sorry for the delay. I have checked the issue. The problem was the old runtime with version4.6, which is not compatible to your antlr4.7. I have resolved that by changing the runtime to 4.7. Please try it again. I have additionally tried to improve the documentation, so this will not happen again. Could you please check, if everything is working well? I would then like to merge this branch, so the improvements are available in the master branch.

**Comment by ivan-gavran** [comment]
Hi,
I checked the procedure and it works well, thank you for the help :)
There was a minor typo in the new documentation (but the one that mattered when compiling with antlr) --> submitted a pull request

**Comment by HendrikRoehm** [comment]
Hi gergia, I am glad that it is working. Please feel free to show the results of what you are currently building. I am really interested your work!
